### ISSUE TITLE
System Sequence Diagrams

### ISSUE THREAD

**Issue by ttgil95** [IrtizaDelwar/RiftAnalytics#1]
Need System Sequence Diagram for each UC as followed:
UC 1: Search user by region
UC 2: Specific Champion Mastery
UC 3: Entire Champion Mastery
UC 4: Ranked Seasonal Stats
UC 5: User Champion Statistics
UC 6: Ranked Team Stats
UC 7: Match History
UC 8: Champion Composition Suggestion
UC 9: Live Match Predictor
UC 10: Champion Analytics
UC 11: Top 5 Lists
UC 12: Free Champion Rotation
UC 13: Ranking Ladder
UC 14: Ultimate Bravery
UC 15: Item Information
UC 16: Frequently Asked Questions

**Comment by IrtizaDelwar** [comment]
Created drafts of Diagrams and met with TA on 10/25

Need to revise too add processor between user and database

**Comment by ttgil95** [comment]
Zargo files for System Sequence Diagrams 1-5

[System Sequence Diagrams 1-5.zip](https://github.com/IrtizaDelwar/RiftAnalytics/files/560127/System.Sequence.Diagrams.1-5.zip)

**Comment by ttgil95** [comment]
PDF of all the system sequence diagrams
[System Sequence Diagrams All.pdf](https://github.com/IrtizaDelwar/RiftAnalytics/files/565462/System.Sequence.Diagrams.All.pdf)

**Comment by ttgil95** [comment]
PDF of the architecture diagram and explanation of each of the layers.
[Architecture Diagram.pdf](https://github.com/IrtizaDelwar/RiftAnalytics/files/565463/Architecture.Diagram.pdf)

**Comment by ttgil95** [comment]
Reviewed diagrams and submitted. Closing issue
