### ISSUE TITLE
search user name

### ISSUE THREAD

**Issue by IrtizaDelwar** [IrtizaDelwar/RiftAnalytics#13]
if there is a space in the username for search, it doesnt work.

**Comment by myyeowoo** [comment]
if you don't type anything in search and press the button, it gives  you an error

**Comment by IrtizaDelwar** [comment]
Made it so it checks the user name is atleast length 1.

But we still need a isValid username method probably.

**Comment by IrtizaDelwar** [comment]
Check added for spaces, <30 accounts, and bad usernames
