### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by ttgil95** [IrtizaDelwar/RiftAnalytics#2]

**Comment by IrtizaDelwar** [comment]
Planning on using 3-Layer architecture with (user, process, and database)

**Comment by ttgil95** [comment]
PDF of the architecture diagram and explanation of each of the layers.
[Architecture Diagram.pdf](https://github.com/IrtizaDelwar/RiftAnalytics/files/565464/Architecture.Diagram.pdf)

**Comment by ttgil95** [comment]
Reviewed architecture diagram and submitted. Closing issue
