### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by IrtizaDelwar** [IrtizaDelwar/RiftAnalytics#3]

**Comment by myyeowoo** [comment]
Classes: Processor, Item, Match, Champion, User

**Comment by myyeowoo** [comment]
***_Item**_*
**fields**
private int itemID
private String name
private String description
private Dictionary stats
**methods**
public int getItemID()
public String getName()
public String getDescription()
public String getStats()
public void setItemID()
public void setName()
public void setDescription()
public void setStats()

**Comment by myyeowoo** [comment]
**_Match**_
**fields**
private int matchID
private String matchMode
private List<Player> players
**methods**
public int getID()
private String getMode()
private List<Player> getPlayers()
public void setID()
public void setMode()
public void setPlayers()

**Comment by myyeowoo** [comment]
Classes: Processor, Item, Match, Champion, User **+Player**

**Comment by myyeowoo** [comment]
**Player**
**fields**
private Champion champion
private User user
private List<Items> item
**methods**
public Champion getChamp()
public User getUser()
public List<Items> getItems()
public void setChamp()
public void setUser()
public void setItems()

**Comment by IrtizaDelwar** [comment]
_Champion_
**fields**
private int championID
private string name
private string passive
private string[] spells
**methods**
public int getID()
public string getName()
public string getPassive()
public string[] getSpells()
public void setID()
public void setName()
public void setPassive()
public void setSpells()

**Comment by ttgil95** [comment]
Detailed Class Diagram
[Class Diagram Updated.zip](https://github.com/IrtizaDelwar/RiftAnalytics/files/576966/Class.Diagram.Updated.zip)

**Comment by IrtizaDelwar** [comment]
Need to add short description

**Comment by ttgil95** [comment]
added the short description and submitted
