### ISSUE TITLE
Database tables

### ISSUE THREAD

**Issue by IrtizaDelwar** [IrtizaDelwar/RiftAnalytics#5]

**Comment by IrtizaDelwar** [comment]
Tables: Username, Champion, Item, Match

**Comment by myyeowoo** [comment]
![classdiagram](https://cloud.githubusercontent.com/assets/10971605/20082924/59883be2-a527-11e6-949e-ec60fe7eb547.png)

**Comment by myyeowoo** [comment]
[Class.Diagram.Updated.zip](https://github.com/IrtizaDelwar/RiftAnalytics/files/577086/Class.Diagram.Updated.zip)

**Comment by IrtizaDelwar** [comment]
Looks good

**Comment by IrtizaDelwar** [comment]
Nevermind , extra lines that we dont need. and need to add a few more.

**Comment by ttgil95** [comment]
Edited the diagram and submitted it
